# Generated by Django 3.2.7 on 2021-09-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rel_id',
            field=models.IntegerField(default=1),
        ),
    ]
