# Generated by Django 3.2.7 on 2021-09-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0005_alter_question_rel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_answer', models.CharField(max_length=100)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_app.room')),
            ],
        ),
    ]
