# Generated by Django 3.2.7 on 2021-09-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0007_random'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='random',
            new_name='random_str',
        ),
    ]
