# Generated by Django 3.2.7 on 2021-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0008_rename_random_random_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answer',
            name='rel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
