# Generated by Django 3.2.7 on 2021-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0009_student_answer_rel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='random_str',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
