# Generated by Django 3.2.7 on 2021-09-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0010_random_str_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random_str',
            name='name',
        ),
    ]
