# Generated by Django 3.2.7 on 2021-09-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0011_remove_random_str_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_string', models.CharField(max_length=40)),
                ('std_name', models.CharField(max_length=40)),
            ],
        ),
    ]
