# Generated by Django 3.2.7 on 2021-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0012_std_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=40)),
                ('total_ques', models.IntegerField()),
                ('no_correct', models.IntegerField()),
            ],
        ),
    ]
