# Generated by Django 3.2.7 on 2021-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0013_std_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_details',
            name='rel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
