# Generated by Django 3.2.7 on 2021-10-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0014_std_details_rel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_mark',
            name='rel_id',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
