# Generated by Django 3.2.7 on 2021-10-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0015_std_mark_rel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='random_str',
            name='student_id',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
