# Generated by Django 3.2.7 on 2021-10-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0016_random_str_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random_str',
            name='student_id',
        ),
        migrations.AddField(
            model_name='student_answer',
            name='student_id',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
