# Generated by Django 3.2.7 on 2021-10-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0017_auto_20211001_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_mark',
            name='student_id',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
    ]
