# Generated by Django 3.2.7 on 2021-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0018_std_mark_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_auth_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
