# Generated by Django 3.2.7 on 2021-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0019_room_user_auth_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.IntegerField()),
                ('timer', models.TimeField()),
            ],
        ),
    ]
