# Generated by Django 3.2.7 on 2021-10-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0020_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdown',
            name='relation',
            field=models.ForeignKey(default=82, on_delete=django.db.models.deletion.CASCADE, to='exam_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='std_details',
            name='relation',
            field=models.ForeignKey(default=82, on_delete=django.db.models.deletion.CASCADE, to='exam_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='std_mark',
            name='relation',
            field=models.ForeignKey(default=82, on_delete=django.db.models.deletion.CASCADE, to='exam_app.room'),
            preserve_default=False,
        ),
    ]
